### ISSUE TITLE
FF "Chest Outside Upper Jail Cell" Fix

### ISSUE THREAD

**Issue by Najatski** [wooferzfg/tww-rando-tracker#1223]
"Chest Outside Upper Jail Cell" only turns blue when you have the Deku Leaf. Thing is, you can still get to the chest without it. If you let the floor master capture you in the big room in FF, it brings you to the upper cell. You can escape and walk over to the chest and open it.

**Comment by wooferzfg** [comment]
The tracker's logic always matches the randomizer's logic - it pulls the randomizer's logic files directly. This Floormaster trick being excluded from the logic was an intentional design choice.

In the next randomizer version (1.11), there will be settings for "logic difficulty", which will allow having this strategy be in logic: https://github.com/LagoLunatic/wwrando/blob/29d5317740248c8ca76c9cf057c542b7e6c70be2/logic/item_locations.txt#L1203
