### ISSUE TITLE
Add option to mark first magic meter

### ISSUE THREAD

**Issue by JohnDevlopment** [wooferzfg/tww-rando-tracker#959]
When I look at the prerequisites for things that require the deku leaf, they tend to also require a magic meter. However, there is no option to tell the tracker that I got a magic meter.

So according to the tracker, I have a deku leaf, but not a magic meter, and I can't tell it that I do.

Is this a feature that needs to be added, or did I run into a bug?

**Comment by wooferzfg** [comment]
This will be added in #949. You access the tracker for the beta build here: https://www.wooferzfg.me/tww-rando-tracker/version-1.10/ (Note that you *must* paste the permalink from the randomizer for the tracker to load.)

This isn't part of the regular tracker because version 1.10.0 hasn't been released yet.
